<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="robot_hardware" params="prefix">

    <!-- Base Link -->
    <link name="${prefix}base_link"/>

    <!-- Base Footprint -->
    <link name="${prefix}base_footprint"/>

    <!-- Chassis -->
    <link name="${prefix}chassis_link">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 ${PI/2}"/>
        <geometry>
          <mesh filename="file://$(find microros_hardware_interface)/description/urdf/assets/chassis/Chassis.stl"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 ${PI/2}"/>
        <geometry>
          <mesh filename="file://$(find microros_hardware_interface)/description/urdf/assets/chassis/Chassis.stl"/>
        </geometry>
        <cast_shadows>false</cast_shadows>
        <material name="grey"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${base_mass}"/>
          <inertia
            ixx="${0.01952332}" ixy="0.0" ixz="0.0"
            iyy="${0.01450326}" iyz="${-0.00000016}"
            izz="${0.02678084}"/>
        </inertial>
    </link>

    <gazebo reference="chassis_link">
      <material>Gazebo/Grey</material>
    </gazebo>

    <joint name="${prefix}chassis_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}chassis_link"/>
      <origin xyz="0 0 ${.0199 + wheel_radius}" rpy="0 0 ${PI}"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="${damping}"/>
    </joint>

    <joint name="${prefix}base_footprint_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}base_footprint"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <!--front is positive, left is positive-->
    <xacro:wheel name="left" x="0" y="0" z="0" front="-1" side="-1"/>
    <xacro:wheel name="right" x="0" y="0" z="0" front="-1" side="1"/>

    <xacro:dead_wheel name="left_caster" x="0" y="0" z="0" front="1" side="-1"/>
    <xacro:dead_wheel name="right_caster" x="0" y="0" z="0" front="1" side="1"/>
  </xacro:macro>

</robot>
